---
version: 2

before:
  hooks:
    - "go mod tidy"
    - "go generate ./..."

builds:
  - skip: true

changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactors"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "Build & CI"
      regexp: '^.*?(build|ci)(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: Other Work
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

release:
  github:
    owner: ubiquiti-community
    name: go-unifi
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## UniFi Go Client {{ .Tag }} ({{ .Date }})

    Welcome to this release of the UniFi Go Client library!
  footer: |
    ## Installation

    To use this version in your Go project:

    ```bash
    go get github.com/ubiquiti-community/go-unifi@{{ .Tag }}
    ```

    **Full Changelog**: https://github.com/ubiquiti-community/go-unifi/compare/{{ .PreviousTag }}...{{ .Tag }}
  name_template: "{{ .Tag }}"
